// <auto-generated />
using Ecomm.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecomm.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230102205518_AddNewItems")]
    partial class AddNewItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecomm.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategorysC");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hat",
                            Url = "hat"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cap",
                            Url = "cap"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Balaclava",
                            Url = "balaclava"
                        });
                });

            modelBuilder.Entity("Ecomm.Shared.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductsC");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "70% wool / 30% polyester. The Pork Pie from Stetson deliberately dispenses with elaborate details.",
                            ImageUrl = "https://hatroom.pl/images/zoom/802970.jpg",
                            Price = 99.99m,
                            Title = "Uni Pork Pie Wool Hat"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "50% wool / 50% polyester. Fully lined. Unisex model.",
                            ImageUrl = "https://www.crafters.fr/images/stories/virtuemart/tt2016/PS_B635_GREY.jpg",
                            Price = 75.5m,
                            Title = "Chapeau Urban Trilby Grey"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "89% paper fiber / 11% polyester - 6cm brim - Supplied with removable black fabric strip.",
                            ImageUrl = "https://images.crafters.fr/bo/16951_60b0a8a70fd08_PS_KP068_NATURAL.png",
                            Price = 59.99m,
                            Title = "Chapeau Panama Natural"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Warm evenings, ice cream and a baseball cap. And there goes summer! Go for a workout in the sunshine while wearing your adidas cap. AEROREADY wicks away sweat, keeping you feeling fresh on the pitch. The curved visor protects your eyes and the 3 stripes emphasise the sporty character. This product is made from Primegreen, a line of high-quality recycled materials.",
                            ImageUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQE2qQNtsSrONpGXAw7D5I_1zT7Tflso4MGVhTYzgAM4bvMD56OC1i4rCktunQC2wmo9-Q&usqp=CAU",
                            Price = 112.99m,
                            Title = "Baseline Hemp"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Lower your head and keep pedaling through chilly weather. The Thermal Cycling Cap is an essential piece of cold weather cycling gear. Packed with the versatility of a visor and ear flaps, this cap features thermal fabric to keep you riding in the great outdoors all year long.",
                            ImageUrl = "https://trek.scene7.com/is/image/TrekBicycleProducts/ThermalCyclingCap_25037_A_Primary?$responsive-pjpg$&cache=on,on&wid=1920&hei=1440",
                            Price = 39.99m,
                            Title = "Bontrager Thermal"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Cap is made from 100% cotton with a contemporary style and includes a Rip-strap size adjuster. A comfortable and stylish cap that is available in various colours.",
                            ImageUrl = "https://futbokraina.com.ua/image/cache/new/catalog/GS/kepki/black-63745.webp",
                            Price = 200m,
                            Title = "Polo Ralph Lauren"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "A unique balaclava specially designed for winter sports. Made with flat seam technology, it will ensure comfort even during long hours of use. The ergonomic cut created separately for men and women ensures a better fit of the balaclava to the face. ",
                            ImageUrl = "https://img.ltwebstatic.com/images3_pi/2022/09/09/1662702772ca0fdc2c0a9f9aefc547f60ea2c8582c_thumbnail_600x.webp",
                            Price = 99.99m,
                            Title = "Horn Decor"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Provide a great protection for your face,ear and neck in the bad weather. Good for bicycle riding,skiing, or other outdoor sports. Soft and comfortable. Breathable material allows easy breath but ultra protection ldeal for the use when riding,skiing, and other outdoor sports.",
                            ImageUrl = "https://cdn.shopify.com/s/files/1/0634/1335/4713/products/Funny-Knitted-Face-Mask_1_900x.jpg?v=1666779905",
                            Price = 70m,
                            Title = "Gang Bang Balaclava"
                        });
                });

            modelBuilder.Entity("Ecomm.Shared.Products", b =>
                {
                    b.HasOne("Ecomm.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
